spring:
  application:
    name: crazy-chat
  graphql:
    http:
      sse:
        keep-alive: 60s
  rabbitmq:
    host: localhost
    username: guest
    password: guest
  mongodb:
    uri: mongodb://root:example@localhost:27017/crazy_chat?authSource=admin
  minio:
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin